spring:
    application:
        name: currency-conversion-service
    cloud:
        config: http://localhost:8888


currency-exchange-service:
    ribbon:
        listOfServers: http://localhost:8002;http://localhost:8003 