spring:
    application:
        name: currency-conversion-service
    cloud:
        config: http://localhost:8888

#With Eureka-Ribbon config is not necesary to config each URL of microservice
#currency-exchange-service:
#    ribbon:
#        listOfServers: http://localhost:8002,http://localhost:8003 