spring:
    application:
        name: currency-exchange-service
    cloud:
        config: http://localhost:8888
    jpa:
        show: true    
    h2:
        console:
            enabled: true/currency-converter-feign/from/USD/to/INR/quantity/1000